# Generated by Django 2.1.5 on 2019-01-28 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remiljscrumy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrumygoals',
            options={'verbose_name': 'Scrumy Goal', 'verbose_name_plural': 'Scrumy Goals'},
        ),
    ]
